# Docker Compose setup for local development

version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/costopt
      - AWS_REGION=us-east-1
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: costopt
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard:
    build: ./dashboard
    container_name: dashboard_ui
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  pgdata: